"use client"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './header/header'
import { Provider } from 'react-redux'
import { store } from './redux/storeReducer'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import { NextUIProvider } from '@nextui-org/react'

const inter = Inter({ subsets: ['latin'] })


// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({

  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <NextUIProvider>{children}</NextUIProvider>
        </Provider>
      </body>

    </html>

  )
}
